{"uuid":"737b0ca4-2f92-48d3-80a2-de2820a3b770","historyId":"194eb684da15acf0f34c58a42db8a5a9","fullName":"api.test.userJourney.ApiTestMethodForUserJourney.executeTest","labels":[{"name":"package","value":"api.test.userJourney.ApiTestMethodForUserJourney"},{"name":"testClass","value":"api.test.userJourney.ApiTestMethodForUserJourney"},{"name":"testMethod","value":"executeTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Rest-Assured-testing-framework"},{"name":"subSuite","value":"project_save with priority 1"},{"name":"host","value":"localhost.localdomain"},{"name":"thread","value":"21826@localhost.localdomain.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"executeTest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Assertion failed: vacancy_save","trace":"java.lang.AssertionError: Assertion failed: vacancy_save\n\tat org.testng.Assert.fail(Assert.java:87)\n\tat api.test.userJourney.ApiTestMethodForUserJourney.executeTest(ApiTestMethodForUserJourney.java:105)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\n\tat org.testng.TestRunner.run(TestRunner.java:596)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\n\tat org.testng.TestNG.run(TestNG.java:1031)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\nCaused by: java.lang.AssertionError: Expected status code 200 but got 403 expected [200] but found [403]\n\tat org.testng.Assert.fail(Assert.java:99)\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\n\tat org.testng.Assert.assertEquals(Assert.java:122)\n\tat org.testng.Assert.assertEquals(Assert.java:907)\n\tat api.test.userJourney.ApiTestMethodForUserJourney.executeTest(ApiTestMethodForUserJourney.java:87)\n\t... 27 more\n"},"stage":"finished","steps":[{"name":"Test failed due to assertion error: Expected status code 200 but got 403 expected [200] but found [403]","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1724172823916,"stop":1724172823917}],"attachments":[],"parameters":[],"start":1724172822952,"stop":1724172823919}